# Metadata
name: Lemuel De Los Santos
email: lemueld6200@afsenyc.org
github_username: lemueld6200
title: "Lemuel De Los Santos' Portfolio"
description: "A Portfolio for Lemuel De Los Santos"
show_excerpts: true

minima:
  date_format: "%b %-d, %Y"

  social_links:
    github: lemueld6200
    rss: rss

# Third party services
# (Anything you put here will be public!)
google-analytics:

header_pages:
  - pages/index.md
  - pages/about.md

# Build settings
theme: minima
encoding: utf-8
markdown: kramdown
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-redirect-from
exclude:
  - .sass-cache/
  - node_modules/
  - .gitignore
  - Gemfile
  - _config.yml
  - glitch.json
  - package.json
  - package-lock.json
  - watch.json
  - "*.save.*"

# paginate: 5
# paginate_path: "/:num/"
permalink: /:year/:month/:day/:title
