# Metadata
name: Lemuel De Los Santos
email: lemueld6200@afsenyc.org
github_username: lemueld6200
title: Lemuel De Los Santos' Portfolio
description: This is a portfolio for my AP Computer Science for my sophomore year of high school.
tags: [portfolio, lemueld6200]
show_excerpts: true

minima:
  date_format: "%b %-d, %Y"

  social_links:
    github: lemueld6200
    rss: rss

disqus:
  shortname: https-portfolio-lemueld6200-glitch-me

google-analytics:

header_pages:
  - pages/index.md
  - pages/about.md
  - posts/index.html

# Build settings
theme: minima
encoding: utf-8
markdown: kramdown
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-redirect-from
exclude:
  - .sass-cache/
  - node_modules/
  - .gitignore
  - Gemfile
  - _config.yml
  - glitch.json
  - package.json
  - package-lock.json
  - watch.json
  - "*.save.*"

paginate: 999
paginate_path: /posts/:num/
permalink: /:year/:month/:day/:title
